name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 18

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        
      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  package:
    name: Package Release
    needs: build
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            packageTask: packageReleaseDeb
          - os: macos-latest
            packageTask: packageReleaseDmg
          - os: windows-latest
            packageTask: packageReleaseMsi
    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 18

      - name: Create release package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ matrix.platform.packageTask }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.packageTask }}
          path: build/compose/binaries/main-release